{
  "train_data_paths": ['/weka/home-jinwooahn/idxs/merge-Blog',
  '/weka/home-jinwooahn/idxs/merge-Community',
  '/weka/home-jinwooahn/idxs/merge-Dialogue',
  '/weka/home-jinwooahn/idxs/merge-Encyclopedia',
  '/weka/home-jinwooahn/idxs/merge-Miscellaneous',
  '/weka/home-jinwooahn/idxs/merge-News',
  '/weka/home-jinwooahn/idxs/merge-Prose',
  '/weka/home-jinwooahn/idxs/merge-Web',
  '/weka/home-jinwooahn/idxs/refined-00.jsonl_text_document',
  '/weka/home-jinwooahn/idxs/refined-01.jsonl_text_document',
  '/weka/home-jinwooahn/idxs/refined-02.jsonl_text_document',
  '/weka/home-jinwooahn/idxs/refined-03.jsonl_text_document',
  '/weka/home-jinwooahn/idxs/refined-04.jsonl_text_document',
  '/weka/home-jinwooahn/idxs/refined-05.jsonl_text_document',
  '/weka/home-jinwooahn/idxs/refined-06.jsonl_text_document',
  '/weka/home-jinwooahn/idxs/refined-07.jsonl_text_document',
  '/weka/home-jinwooahn/idxs/refined-08.jsonl_text_document',
  '/weka/home-jinwooahn/idxs/refined-09.jsonl_text_document',
  '/weka/home-jinwooahn/idxs/refined-10.jsonl_text_document',
  '/weka/home-jinwooahn/idxs/refined-11.jsonl_text_document',
  '/weka/home-jinwooahn/idxs/refined-13.jsonl_text_document',
  '/weka/home-jinwooahn/idxs/refined-14.jsonl_text_document',
  '/weka/home-jinwooahn/idxs/refined-15.jsonl_text_document',
  '/weka/home-jinwooahn/idxs/refined-16.jsonl_text_document',
  '/weka/home-jinwooahn/idxs/refined-17.jsonl_text_document',
  '/weka/home-jinwooahn/idxs/refined-18.jsonl_text_document',
  '/weka/home-jinwooahn/idxs/refined-19.jsonl_text_document',
  '/weka/home-jinwooahn/idxs/refined-20.jsonl_text_document',
  '/weka/home-jinwooahn/idxs/refined-21.jsonl_text_document',
  '/weka/home-jinwooahn/idxs/refined-22.jsonl_text_document',
  '/weka/home-jinwooahn/idxs/refined-23.jsonl_text_document',
  '/weka/home-jinwooahn/idxs/refined-24.jsonl_text_document',
  '/weka/home-jinwooahn/idxs/refined-25.jsonl_text_document',
  '/weka/home-jinwooahn/idxs/refined-26.jsonl_text_document',
  '/weka/home-jinwooahn/idxs/refined-27.jsonl_text_document',
  '/weka/home-jinwooahn/idxs/refined-28.jsonl_text_document',
  '/weka/home-jinwooahn/idxs/refined-30.jsonl_text_document',
  '/weka/home-jinwooahn/idxs/slim-pajama_text_document',
  '/weka/home-jinwooahn/idxs/the-stack-dedup-01_text_document'],
  "train_data_weights": [2179.037246,
  133.1279,
  0.6580,
  24.4105,
  93.5836,
  266.5269,
  78.5888,
  294.1938,
  159.7153,
  160.5517,
  160.5362,
  160.6355,
  159.8202,
  160.8010,
  160.5858,
  158.9365,
  158.8516,
  158.7736,
  158.4286,
  159.0938,
  159.2720,
  158.8843,
  158.8274,
  157.8932,
  159.3024,
  159.3323,
  158.0635,
  158.9889,
  159.0800,
  159.9745,
  159.2578,
  161.4557,
  158.7702,
  158.4028, 
  158.7384,
  159.3969,
  0.000008,
  1779.7136,
  687.7878],
  # use small scale (50B) dataset as valid and test set.
  "valid_data_paths": ["/admin/home-jinwooahn/repos/data/indexes/mmap/small_exp_50B"],
  "test_data_paths": ["/admin/home-jinwooahn/repos/data/indexes/mmap/small_exp_50B"],
  # upsample Korean data
  "data_impl": "s3",
  "vocab_file": "/weka/home-jinwooahn/tokenizer/polyglot_bpe_50k.json",
  "save": "/weka/home-jinwooahn/polyglot-v2/checkpoints",  # if this is not set, checkpoint does not save at all
  "s3_path": "s3://polyglot-korean-west/polyglot-v2",
  "checkpoint_validation_with_forward_pass": false,
  "tensorboard_dir": "tensorboard",
  "log_dir": "logs",
  "launcher": "slurm",
  "deepspeed_slurm": true,
  "no_ssh_check": true,
  "use_wandb": true,
  "wandb_host": "https://api.wandb.ai",
  "wandb_project": "polyglot-v2-7B"
}